apiVersion: v1
kind: Service
metadata:
  name: ops-proxy
  namespace: ops-system
  labels:
    app: ops-proxy
    component: ops-proxy
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: proxy
    port: 6443
    targetPort: 6443
    protocol: TCP
  selector:
    app: ops-proxy
    component: ops-proxy

